package server

import (
	"fmt"
	"strings"
)

var guidelinesDB = map[string]string{
	"sql injection": `## SQL Injection Prevention

### Overview
SQL injection occurs when untrusted data is sent to an interpreter as part of a command or query.

### Prevention Rules
1. **Use Parameterized Queries (Prepared Statements)** - #1 defense
2. **Use Stored Procedures** - When parameterized queries aren't possible
3. **Validate Input** - Whitelist validation for expected input
4. **Escape All User-Supplied Input** - Last resort only

### Examples

**Python:**
` + "```python" + `
# BAD
cursor.execute(f"SELECT * FROM users WHERE id = {user_id}")
# GOOD
cursor.execute("SELECT * FROM users WHERE id = %s", (user_id,))
` + "```" + `

**JavaScript (Node.js):**
` + "```javascript" + `
// BAD - db.query(` + "`SELECT * FROM users WHERE id = ${userId}`" + `)
// GOOD
db.query("SELECT * FROM users WHERE id = $1", [userId])
` + "```" + `

**Go:**
` + "```go" + `
// BAD
db.Query(fmt.Sprintf("SELECT * FROM users WHERE id = %d", id))
// GOOD
db.Query("SELECT * FROM users WHERE id = $1", id)
` + "```" + `

### References
- [OWASP SQL Injection Prevention](https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html)
- CWE-89`,

	"xss": `## Cross-Site Scripting (XSS) Prevention

### Types
1. **Reflected XSS** - Script from the current HTTP request
2. **Stored XSS** - Script stored on the server
3. **DOM-based XSS** - Script execution via client-side JavaScript

### Prevention Rules
1. **Escape Output** - HTML encode all untrusted data
2. **Use Content Security Policy (CSP)** - Restrict script sources
3. **Use HTTPOnly Cookies** - Prevent JavaScript cookie access
4. **Use Modern Frameworks** - React, Vue, Angular auto-escape by default

### CSP Header Example
` + "```" + `
Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'
` + "```" + `

### References
- [OWASP XSS Prevention](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html)
- CWE-79`,

	"command injection": `## OS Command Injection Prevention

### Prevention Rules
1. **Avoid System Calls** - Use language-native libraries instead of shell commands
2. **Don't Use Shell=True** - Always pass arguments as arrays/lists
3. **Validate Input** - Whitelist allowed characters (alphanumeric only)
4. **Use execFile, not exec** - execFile doesn't spawn a shell

### Examples
` + "```python" + `
# BAD
os.system(f"ping {host}")
# GOOD
subprocess.run(["ping", "-c", "1", host], shell=False)
` + "```" + `

### References
- [OWASP Command Injection Defense](https://cheatsheetseries.owasp.org/cheatsheets/OS_Command_Injection_Defense_Cheat_Sheet.html)
- CWE-78`,

	"authentication": `## Authentication Best Practices

### Password Storage
1. **Use bcrypt, scrypt, or Argon2** - Never MD5 or SHA-256 alone
2. **Salt passwords** - Unique per-user salt (auto-generated by bcrypt)
3. **Enforce strong passwords** - Min 8 chars, check against breached password lists

### Session Management
1. **Regenerate session ID after login** - Prevents session fixation
2. **Set secure cookie flags** - HttpOnly, Secure, SameSite=Strict
3. **Implement session timeout** - Both idle (15min) and absolute (8h)

### Multi-Factor Authentication
1. **Implement MFA for sensitive operations**
2. **Use TOTP (RFC 6238)** - Not SMS (vulnerable to SIM swapping)
3. **Provide recovery codes** - Single-use, stored hashed

### JWT Best Practices
1. **Use RS256 or ES256** - Never "none" algorithm
2. **Validate all claims** - iss, aud, exp, nbf
3. **Keep tokens short-lived** - 15 min access, 7 day refresh
4. **Store in HttpOnly cookies** - Not localStorage

### References
- [OWASP Authentication Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html)`,

	"input validation": `## Input Validation Best Practices

### Principles
1. **Validate on the server** - Client-side validation is only for UX
2. **Whitelist over blacklist** - Define what IS allowed
3. **Validate type, length, range, and format**
4. **Reject invalid input** - Don't sanitize and accept

### Techniques
1. **Type checking** - Ensure integers are integers
2. **Length limits** - Set maximum and minimum lengths
3. **Range validation** - Numbers within expected bounds
4. **Regex patterns** - For formatted strings (email, phone)
5. **Encoding validation** - Ensure proper UTF-8
6. **Canonicalization** - Normalize before validation

### References
- [OWASP Input Validation](https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html)`,

	"csrf": `## Cross-Site Request Forgery (CSRF) Prevention

### Overview
CSRF forces authenticated users to execute unwanted actions on a web application.

### Prevention Methods
1. **Synchronizer Token Pattern** - Include unique token in forms
2. **Double Submit Cookie** - Token in both cookie and request
3. **SameSite Cookie Attribute** - Set SameSite=Strict or Lax
4. **Check Origin/Referer Headers** - Verify request origin

### Implementation
` + "```python" + `
# Django - CSRF middleware enabled by default
# In templates: {% csrf_token %}

# Flask
from flask_wtf.csrf import CSRFProtect
csrf = CSRFProtect(app)
` + "```" + `

` + "```javascript" + `
// Express.js
const csrf = require("csurf");
app.use(csrf({ cookie: true }));
` + "```" + `

### References
- [OWASP CSRF Prevention](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html)
- CWE-352`,

	"secrets management": `## Secrets Management

### Rules
1. **Never hardcode secrets** - Use environment variables or secret managers
2. **Never commit secrets to git** - Use .gitignore and pre-commit hooks
3. **Rotate secrets regularly** - Automate rotation where possible
4. **Use different secrets per environment** - Dev, staging, prod
5. **Encrypt secrets at rest** - Use KMS, Vault, or equivalent

### Tools
- **AWS Secrets Manager** / **GCP Secret Manager** / **Azure Key Vault**
- **HashiCorp Vault** - Self-hosted secrets management
- **SOPS** - Encrypted files for git
- **git-secrets** - Pre-commit hook to prevent secret commits
- **detect-secrets** - Yelp's secret detection tool

### .gitignore Must-Haves
` + "```" + `
.env
.env.local
.env.*.local
*.pem
*.key
credentials.json
service-account.json
` + "```" + `

### References
- [OWASP Secrets Management](https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html)
- CWE-798`,

	"cryptography": `## Cryptography Best Practices

### Hashing
- **Passwords:** bcrypt, scrypt, Argon2id (NEVER MD5, SHA-1, SHA-256 alone)
- **Data integrity:** SHA-256, SHA-3, BLAKE2
- **HMAC:** For message authentication

### Encryption
- **Symmetric:** AES-256-GCM (authenticated encryption)
- **Asymmetric:** RSA-2048+ or Ed25519/X25519
- **TLS:** 1.2+ minimum, prefer 1.3

### What NOT to Do
1. Don't implement your own crypto
2. Don't use ECB mode
3. Don't use DES, 3DES, RC4, MD5, SHA-1
4. Don't reuse nonces/IVs
5. Don't use predictable random for crypto (use crypto/rand, secrets module)

### Random Number Generation
` + "```python" + `
# BAD
import random
token = random.randint(0, 999999)

# GOOD
import secrets
token = secrets.token_urlsafe(32)
` + "```" + `

### References
- [OWASP Cryptographic Storage](https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html)`,

	"cors": `## CORS (Cross-Origin Resource Sharing) Security

### Rules
1. **Never use Access-Control-Allow-Origin: *** for authenticated endpoints
2. **Whitelist specific origins** - Don't reflect the Origin header
3. **Don't expose sensitive headers** unnecessarily
4. **Set Access-Control-Max-Age** appropriately

### Secure Configuration
` + "```javascript" + `
// Express.js
const cors = require("cors");
app.use(cors({
  origin: ["https://app.example.com"],
  methods: ["GET", "POST"],
  credentials: true,
  maxAge: 3600
}));
` + "```" + `

### Dangerous Patterns
- Reflecting any Origin header back as allowed
- Allowing null origin
- Using wildcard with credentials

### References
- [OWASP CORS](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Origin_Resource_Sharing_Cheat_Sheet.html)`,

	"path traversal": `## Path Traversal Prevention

### Overview
Path traversal allows attackers to access files outside the intended directory
using sequences like ../../etc/passwd.

### Prevention
1. **Validate input** - Reject paths containing ".."
2. **Canonicalize paths** - Resolve to absolute path, then check prefix
3. **Use chroot/sandboxing** - Restrict filesystem access
4. **Whitelist allowed characters** - Only alphanumeric, hyphens, underscores

### Example
` + "```go" + `
func serveSafe(baseDir, userPath string) error {
    clean := filepath.Clean(userPath)
    full := filepath.Join(baseDir, clean)
    abs, _ := filepath.Abs(full)
    if !strings.HasPrefix(abs, baseDir) {
        return errors.New("path traversal detected")
    }
    return serveFile(abs)
}
` + "```" + `

### References
- [OWASP Path Traversal](https://cheatsheetseries.owasp.org/cheatsheets/Path_Traversal_Cheat_Sheet.html)
- CWE-22`,

	"deserialization": `## Insecure Deserialization Prevention

### Overview
Deserializing untrusted data can lead to remote code execution, DoS,
or privilege escalation.

### Rules
1. **Never deserialize untrusted input** with native serialization
2. **Use JSON instead of native serialization** where possible
3. **If you must deserialize, validate and sanitize** before processing
4. **Implement integrity checks** - Sign serialized objects

### Dangerous Functions
- **Python:** pickle.loads(), yaml.load() (use yaml.safe_load())
- **Java:** ObjectInputStream.readObject()
- **PHP:** unserialize()
- **Ruby:** Marshal.load()
- **Node.js:** node-serialize (avoid entirely)

### Safe Alternatives
` + "```python" + `
# BAD
import pickle
data = pickle.loads(untrusted_input)

# GOOD
import json
data = json.loads(untrusted_input)

# If YAML needed:
import yaml
data = yaml.safe_load(untrusted_input)  # NOT yaml.load()
` + "```" + `

### References
- [OWASP Deserialization](https://cheatsheetseries.owasp.org/cheatsheets/Deserialization_Cheat_Sheet.html)
- CWE-502`,

	"logging": `## Secure Logging Best Practices

### What to Log
1. Authentication events (login, logout, failed attempts)
2. Authorization failures
3. Input validation failures
4. Application errors and exceptions
5. Security-relevant configuration changes

### What NOT to Log
1. Passwords or credentials
2. Session tokens or API keys
3. Credit card numbers (PCI DSS)
4. Personal data (GDPR: emails, addresses, etc.)
5. Full stack traces in production (expose internals)

### Log Injection Prevention
` + "```python" + `
# BAD - allows log injection
logger.info(f"User login: {username}")

# GOOD - sanitize newlines
safe_user = username.replace('\n', '').replace('\r', '')
logger.info("User login: %s", safe_user)
` + "```" + `

### Structured Logging
` + "```python" + `
import structlog
logger = structlog.get_logger()
logger.info("user_login", user_id=user.id, ip=request.remote_addr)
` + "```" + `

### References
- [OWASP Logging Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html)`,

	"error handling": `## Secure Error Handling

### Rules
1. **Don't expose stack traces** in production
2. **Use generic error messages** for users
3. **Log detailed errors server-side** for debugging
4. **Don't reveal system information** in error responses
5. **Handle all exceptions** - Don't leave unhandled paths

### API Error Response Pattern
` + "```json" + `
{
  "error": {
    "code": "VALIDATION_ERROR",
    "message": "Invalid input provided",
    "request_id": "abc-123"
  }
}
` + "```" + `

Never return:
` + "```json" + `
{
  "error": "SQL error near line 42: SELECT * FROM users WHERE...",
  "stack": "at db.query (db.js:42)\nat handler (routes.js:15)..."
}
` + "```" + `

### Framework Configuration
` + "```python" + `
# Django
DEBUG = False  # NEVER True in production
ADMINS = [("Admin", "admin@example.com")]
` + "```" + `

` + "```javascript" + `
// Express.js - custom error handler
app.use((err, req, res, next) => {
  logger.error({ err, requestId: req.id });
  res.status(500).json({ error: { message: "Internal server error", request_id: req.id } });
});
` + "```" + `

### References
- [OWASP Error Handling](https://cheatsheetseries.owasp.org/cheatsheets/Error_Handling_Cheat_Sheet.html)`,

	"api security": `## API Security Best Practices

### Authentication
1. Use OAuth 2.0 / OpenID Connect for user-facing APIs
2. Use API keys + HMAC signatures for service-to-service
3. Never pass credentials in URL query parameters

### Rate Limiting
1. Implement per-user and per-IP rate limits
2. Return 429 Too Many Requests with Retry-After header
3. Use sliding window or token bucket algorithms

### Input/Output
1. Validate all input against a schema (JSON Schema, OpenAPI)
2. Limit request body size
3. Paginate list endpoints (max 100 items)
4. Don't return more data than the client needs

### Headers
` + "```" + `
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
Strict-Transport-Security: max-age=31536000; includeSubDomains
Content-Security-Policy: default-src 'self'
` + "```" + `

### References
- [OWASP REST Security](https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html)
- [OWASP API Security Top 10](https://owasp.org/www-project-api-security/)`,

	"docker security": `## Docker/Container Security

### Image Security
1. Use minimal base images (alpine, distroless, scratch)
2. Don't run as root - use USER directive
3. Pin image versions - never use :latest in production
4. Scan images for vulnerabilities (Trivy, Snyk)

### Dockerfile Best Practices
` + "```dockerfile" + `
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .

FROM node:20-alpine
RUN addgroup -S app && adduser -S app -G app
USER app
WORKDIR /app
COPY --from=build /app .
EXPOSE 3000
CMD ["node", "server.js"]
` + "```" + `

### Runtime Security
1. Use read-only root filesystem
2. Drop all capabilities, add only needed ones
3. Set resource limits (memory, CPU)
4. Don't mount Docker socket into containers
5. Use network policies to restrict container communication

### References
- [OWASP Docker Security](https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html)`,
}

func getGuidelines(topic, language string) string {
	topicLower := strings.ToLower(strings.TrimSpace(topic))

	// Direct match
	if guide, ok := guidelinesDB[topicLower]; ok {
		return guide
	}

	// Fuzzy match
	for key, guide := range guidelinesDB {
		if strings.Contains(topicLower, key) || strings.Contains(key, topicLower) {
			return guide
		}
	}

	// Keyword match
	keywords := strings.Fields(topicLower)
	for key, guide := range guidelinesDB {
		for _, kw := range keywords {
			if len(kw) > 3 && strings.Contains(key, kw) {
				return guide
			}
		}
	}

	// List available topics
	var topics []string
	for key := range guidelinesDB {
		topics = append(topics, key)
	}

	return fmt.Sprintf("## Security Guidelines\n\nNo specific guidelines found for: %q\n\n"+
		"**Available topics:**\n%s\n\n"+
		"Use `scan_code` to analyze your codebase for specific vulnerabilities.",
		topic, formatTopicList(topics))
}

func formatTopicList(topics []string) string {
	var sb strings.Builder
	for _, t := range topics {
		sb.WriteString(fmt.Sprintf("- %s\n", t))
	}
	return sb.String()
}
